name: Publish
on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      generate-build-number: false
      conventional-commits-publish-conditions: false
      enable-caching: false
      additional-test-arguments: '--logger GitHubActions'
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [publish]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release
        run: gh release create ${{ github.ref_name }}
          --title "${{ github.ref_name }}"
          --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}